name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        default: none
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pseudo Deployment
        run: echo "Deploying App"
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output artifacts
        run: ls

    # Comment the rest