name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World"
          sleep 120
          echo "Another line"
      - name: Print a second step
        shell: python
        run: print("Woaw a python line")